### ISSUE TITLE
Error: Cannot find module '@angular-devkit/core'

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/igniteui-cli#135]
### Description  
Using IgniteUI CLI to quickstart an Angular project, what's generated will not initially run. I believe this is related to https://github.com/angular/angular-cli/issues/9307. The fix provided in the comments there works, which leads me to believe that we need to either update the angular-cli referenced in the ig-cli or use "^" on the reference.

### Steps to reproduce  

1. create a new ig-ng project (ig new test-project --framework=angular)
2. npm install
3. npm start

### Result  
Will not run, first error thrown:
Error: Cannot find module '@angular-devkit/core'

### Expected result  
Compiles and runs out of the box.

**Comment by jVanZwieten** [comment]
The current workaround for this is:
## New Projects
1. `ig new new-project --framework=angular`
2. open package.json, replace `"@angular/cli": "1.5.3",` with `"@angular/cli": "^1.5.3",`
3. npm install
4. npm start

## Current Projects
1. open package.json, replace `"@angular/cli": "1.5.3",` with `"@angular/cli": "^1.5.3",`
2. npm update
3. npm start

**Comment by damyanpetev** [comment]
Yup that's the issue that (due to weak dependency ~0.0.x) crept down affecting previous Angular CLI projects. I've already bumped the project template version to latest 1.6.5 (the only one that'll work anyway). Coming with updates for #136. 
Not sure we want to allow it to pick up newer versions - Angular CLI generates projects with fixed versions for a reason. Probably to avoid breaking projects with newer releases, though this happened 🤔
