### ISSUE TITLE
Support npm dependencies into CLI template

### ISSUE THREAD

**Issue by bazal4o** [IgniteUI/igniteui-cli#192]
As a developer I need to be able to provide npm package as a dependency for my template/custom template

**Comment by damyanpetev** [comment]
At this point I'm leaning towards adding another property to the Template interface (thus to the [extensibility json](https://github.com/IgniteUI/igniteui-cli/wiki/Extensibility-Support#configure-templatejson) too), rather than extending existing ones.
For example `packages` /`packageDependencies` as a string array.
So we could have a config  combination of something like:
```json
{
  packages: ["my-awesome-package"],
  dependencies: [{ "import": "AwesomeModule", "from": "my-awesome-package } ]
}
```
@sbozalieva @StefanIvanov @kdinev Thoughts on extra property and naming?

**Comment by StefanIvanov** [comment]
I think your naming is clear and concise enough and have no remarks
