### ISSUE TITLE
Support add component to a specific module

### ISSUE THREAD

**Issue by bazal4o** [IgniteUI/igniteui-cli#273]
As I developer I want to be able to choose (step-by-step ?)/provide (command) - module where I want to add the view. 
It could be `add <template> <name> --module=myCustomModule`
similar to `ng g component nameComponent --module=app.module.ts`

**Comment by ViktorSlavov** [comment]
Currently, when adding a component declaration to the main module, we are assuming that common modules such as `FormsModule`, `CommonModule`, etc are included and they are missing from the component templates. If a template is added to a custom module and the above modules are **not** defined, the module will not properly compile.
Each template needs to have its dependencies added explicitly in order to fully support adding to custom modules.
Currently, the module will properly compile only after all dependencies are added.
