### ISSUE TITLE
Running the "ig" command in Visual Studio is freezing the console

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-cli#536]
### Description  
When you try to run the step by step guide in the Package Manager Console it freezes.

- Ignite UI CLI version: 4.2.x
- Framework: Angular
- Project type: igx-ts

### Steps to reproduce  

1. Create a new Nodejs project in VS 2019
2. Run `ig` inside the Package Manager Console

### Result  
The console freezes at
```
PM> ig
Starting Step by step mode.
For available commands, stop this execution and use --help.
```

### Expected result  
You are prompted to provide a name for your project

Note: If you use 
`ig new newIgniteUIAngular --framework=angular --type=igx-ts`
the project is created successfully

**Comment by ViktorSlavov** [comment]
This is an issue with the **NuGet Package Manager Console** itself.

Its primary function is to manage (install/change/uninstall/etc.) NuGet packages for you project and it's meant to run [PowerShell commands](https://docs.microsoft.com/en-us/nuget/reference/powershell-reference).

While it does support `node` commands, if you try to run a node script that requires user input the console will freeze. This is the case when running `ig`, as well as many other (`ng new`, `npm init`, etc.).

It is a [known issue](https://github.com/aspnet/Tooling/issues/329#issuecomment-165314589) that the **NuGet Package Manager Consol**e freezes when requiring user input through a node script and it's advised **not** to use it as a general console.

A quick way to test out how the console freezes is:
  1. Create a `promptScript.js` file in your directory, with the following content:
```javascript
var stdin = process.stdin;

console.log("Please input text in command line.");

stdin.on('data', function (data) {
    // User input exit.
    if (data === 'exit\n') {
        // Program exit.
        console.log("User input complete, program exit.");
        process.exit();
    } else {
        // Print user input in console.
        console.log('User Input Data : ' + data);
    }
});
```
  2. Open the **NuGet Package Manager Console** and execute the script by running `node promptScript.js`
  3. After the prompt for user input, the `npmc` will freeze

The freeze happens because the console [does not support stdio redirection](https://stackoverflow.com/a/24071161) - the process created by the **NuGet Package Manager Console** cannot catch the input awaited by the `node` script.
