### ISSUE TITLE
Update the templates affected by the drag/drop refactoring

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-cli#570]
### Description  
Deprecation warnings are shown when creating and opening a template that uses the IgxDragDirective deprecated properties.

- Ignite UI CLI version: 4.3.0
- Framework: Angular
- Project type: igx-ts

### Steps to reproduce  

1. Create an Angular project and add a basic grid template
2. Observe the Console after navigating to the template

### Result  
The following warnings are displayed:
IgxDragDirective.hideBaseOnDrag: 'hideBaseOnDrag' @Input property is deprecated and will be removed in future major versions.
        Alternatives to it are using the new no ghost dragging and custom base styling.
showMessage @ igniteui-angular.js:7133

IgxDragDirective.animateOnRelease: 'animateOnRelease' @Input property is deprecated and will be removed in future major versions.
        Please use 'transitionToOrigin' or 'transitionTo' methods instead.

### Expected result  
No warnings are shown.

**Comment by Lipata** [comment]
Related to #578

**Comment by ViktorSlavov** [comment]
This does not seem to be related to the templates. The grid and chip components (the ones I've found so far) use the deprecated properties internally and that's why the warning are appearing.

The same warning appears when running the dev-demos app or when opening the default [grid](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#demo) or [chip](https://stackblitz.com/angular/ldmjgrpndnq) samples on StackBlitz.
