### ISSUE TITLE
Restore original entry selection with all frameworks after Angular Schematics

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-cli#579]
### Description  
Once the Angular Schematics are official in version 5.0.0, perhaps it'd be a good time to restore the original entry selection that'd ask for a framework when creating a project?
My thinking is Ignite UI for Angular would have it's streamlined entry point through schematics and the ig command can again be more broad. The configuration introduced with #423 remains and won't affect existing user config changes, just the defaults.

//CC @kdinev @jberes Thoughts?

**Comment by kdinev** [comment]
@damyanpetev IMO, the original experience with the CLI wizard can be restore only after the new schematics have been released, together with the docs and when we see users moving to schematics instead of the CLI. I think the CLI should also contain a console message when using `new` and `add` for Angular, to try the new ng cli schematics out!
